//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astrila.Eq2ImgWinForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LinkDialogURLs {
            get {
                return ((string)(this["LinkDialogURLs"]));
            }
            set {
                this["LinkDialogURLs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoUpdateFormula {
            get {
                return ((bool)(this["AutoUpdateFormula"]));
            }
            set {
                this["AutoUpdateFormula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormulaImages")]
        public string FormulaImages {
            get {
                return ((string)(this["FormulaImages"]));
            }
            set {
                this["FormulaImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color BackGroundColor {
            get {
                return ((global::System.Drawing.Color)(this["BackGroundColor"]));
            }
            set {
                this["BackGroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color FontColor {
            get {
                return ((global::System.Drawing.Color)(this["FontColor"]));
            }
            set {
                this["FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font ApplicationFont {
            get {
                return ((global::System.Drawing.Font)(this["ApplicationFont"]));
            }
            set {
                this["ApplicationFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("184")]
        public int SplitContainer9Height {
            get {
                return ((int)(this["SplitContainer9Height"]));
            }
            set {
                this["SplitContainer9Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("186")]
        public int SplitContainer8Height {
            get {
                return ((int)(this["SplitContainer8Height"]));
            }
            set {
                this["SplitContainer8Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("327")]
        public int SplitContainer2Height {
            get {
                return ((int)(this["SplitContainer2Height"]));
            }
            set {
                this["SplitContainer2Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("315")]
        public int SplitContainer5Height {
            get {
                return ((int)(this["SplitContainer5Height"]));
            }
            set {
                this["SplitContainer5Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("88")]
        public int SplitContainer7Height {
            get {
                return ((int)(this["SplitContainer7Height"]));
            }
            set {
                this["SplitContainer7Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("88")]
        public int SplitContainer6Height {
            get {
                return ((int)(this["SplitContainer6Height"]));
            }
            set {
                this["SplitContainer6Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int SplitContainer4Height {
            get {
                return ((int)(this["SplitContainer4Height"]));
            }
            set {
                this["SplitContainer4Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87")]
        public int SplitContainer3Height {
            get {
                return ((int)(this["SplitContainer3Height"]));
            }
            set {
                this["SplitContainer3Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("623")]
        public int SplitContainer1Height {
            get {
                return ((int)(this["SplitContainer1Height"]));
            }
            set {
                this["SplitContainer1Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveAllSplitEnabled {
            get {
                return ((bool)(this["SaveAllSplitEnabled"]));
            }
            set {
                this["SaveAllSplitEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoSizePanels {
            get {
                return ((bool)(this["EnableAutoSizePanels"]));
            }
            set {
                this["EnableAutoSizePanels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Alt+F")]
        public global::System.Windows.Forms.Keys OpenFormulaPanel {
            get {
                return ((global::System.Windows.Forms.Keys)(this["OpenFormulaPanel"]));
            }
            set {
                this["OpenFormulaPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Alt+V")]
        public global::System.Windows.Forms.Keys CustomPaste {
            get {
                return ((global::System.Windows.Forms.Keys)(this["CustomPaste"]));
            }
            set {
                this["CustomPaste"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Alt+V")]
        public string CustomPasteKeysDisplay {
            get {
                return ((string)(this["CustomPasteKeysDisplay"]));
            }
            set {
                this["CustomPasteKeysDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("New Century Schoolbook, 8.25pt")]
        public global::System.Drawing.Font DefaultEnglishFont {
            get {
                return ((global::System.Drawing.Font)(this["DefaultEnglishFont"]));
            }
            set {
                this["DefaultEnglishFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHREE-DEV-0708E, 8.25pt")]
        public global::System.Drawing.Font DefaultHindiFont {
            get {
                return ((global::System.Drawing.Font)(this["DefaultHindiFont"]));
            }
            set {
                this["DefaultHindiFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 16")]
        public global::System.Drawing.Point Paragraph_panelCancel {
            get {
                return ((global::System.Drawing.Point)(this["Paragraph_panelCancel"]));
            }
            set {
                this["Paragraph_panelCancel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("111, 16")]
        public global::System.Drawing.Point Paragraph_panelClear {
            get {
                return ((global::System.Drawing.Point)(this["Paragraph_panelClear"]));
            }
            set {
                this["Paragraph_panelClear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("630, 16")]
        public global::System.Drawing.Point Paragraph_panelSave {
            get {
                return ((global::System.Drawing.Point)(this["Paragraph_panelSave"]));
            }
            set {
                this["Paragraph_panelSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("742, 1")]
        public global::System.Drawing.Point Paragraph_Closebutton {
            get {
                return ((global::System.Drawing.Point)(this["Paragraph_Closebutton"]));
            }
            set {
                this["Paragraph_Closebutton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6, 6")]
        public global::System.Drawing.Point ParagraphForQuestions {
            get {
                return ((global::System.Drawing.Point)(this["ParagraphForQuestions"]));
            }
            set {
                this["ParagraphForQuestions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paragraph For Questions")]
        public string TextParagraphForQuestions {
            get {
                return ((string)(this["TextParagraphForQuestions"]));
            }
            set {
                this["TextParagraphForQuestions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("458, 8")]
        public global::System.Drawing.Point Location_checkBox1 {
            get {
                return ((global::System.Drawing.Point)(this["Location_checkBox1"]));
            }
            set {
                this["Location_checkBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Subject")]
        public string TextSelectSubject {
            get {
                return ((string)(this["TextSelectSubject"]));
            }
            set {
                this["TextSelectSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 12")]
        public global::System.Drawing.Point Location_SelectSubject {
            get {
                return ((global::System.Drawing.Point)(this["Location_SelectSubject"]));
            }
            set {
                this["Location_SelectSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("331, 9")]
        public global::System.Drawing.Point Location_SelectSubjectDDL {
            get {
                return ((global::System.Drawing.Point)(this["Location_SelectSubjectDDL"]));
            }
            set {
                this["Location_SelectSubjectDDL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Topic")]
        public string Text_SelectTopic {
            get {
                return ((string)(this["Text_SelectTopic"]));
            }
            set {
                this["Text_SelectTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("603, 12")]
        public global::System.Drawing.Point Location_SelectTopic {
            get {
                return ((global::System.Drawing.Point)(this["Location_SelectTopic"]));
            }
            set {
                this["Location_SelectTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("695, 9")]
        public global::System.Drawing.Point Location_SelectTopicDDL {
            get {
                return ((global::System.Drawing.Point)(this["Location_SelectTopicDDL"]));
            }
            set {
                this["Location_SelectTopicDDL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Answer Option 1")]
        public string ENAnswerOption1 {
            get {
                return ((string)(this["ENAnswerOption1"]));
            }
            set {
                this["ENAnswerOption1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24, 8")]
        public global::System.Drawing.Point Location_ENAnswerOption1 {
            get {
                return ((global::System.Drawing.Point)(this["Location_ENAnswerOption1"]));
            }
            set {
                this["Location_ENAnswerOption1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Answer Option 2")]
        public string ENAnswerOption2 {
            get {
                return ((string)(this["ENAnswerOption2"]));
            }
            set {
                this["ENAnswerOption2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Location_ENAnswerOption2 {
            get {
                return ((global::System.Drawing.Point)(this["Location_ENAnswerOption2"]));
            }
            set {
                this["Location_ENAnswerOption2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AnswerOption 3")]
        public string ENAnswerOption3 {
            get {
                return ((string)(this["ENAnswerOption3"]));
            }
            set {
                this["ENAnswerOption3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15, 5")]
        public global::System.Drawing.Point Location_ENAnswerOption3 {
            get {
                return ((global::System.Drawing.Point)(this["Location_ENAnswerOption3"]));
            }
            set {
                this["Location_ENAnswerOption3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Answer Option 4")]
        public string ENAnswerOption4 {
            get {
                return ((string)(this["ENAnswerOption4"]));
            }
            set {
                this["ENAnswerOption4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Locattion_ENAnswerOption4 {
            get {
                return ((global::System.Drawing.Point)(this["Locattion_ENAnswerOption4"]));
            }
            set {
                this["Locattion_ENAnswerOption4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("उत्तर विकल्प 1")]
        public string HIAnswerOption1 {
            get {
                return ((string)(this["HIAnswerOption1"]));
            }
            set {
                this["HIAnswerOption1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33, 8")]
        public global::System.Drawing.Point Location_HIAnswerOption1 {
            get {
                return ((global::System.Drawing.Point)(this["Location_HIAnswerOption1"]));
            }
            set {
                this["Location_HIAnswerOption1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("उत्तर विकल्प 3")]
        public string HIAnswerOption3 {
            get {
                return ((string)(this["HIAnswerOption3"]));
            }
            set {
                this["HIAnswerOption3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9, 4")]
        public global::System.Drawing.Point Location_HIAnswerOption3 {
            get {
                return ((global::System.Drawing.Point)(this["Location_HIAnswerOption3"]));
            }
            set {
                this["Location_HIAnswerOption3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("उत्तर विकल्प 2")]
        public string HIAnswerOption2 {
            get {
                return ((string)(this["HIAnswerOption2"]));
            }
            set {
                this["HIAnswerOption2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32, 12")]
        public global::System.Drawing.Point Location_HIAnswerOption2 {
            get {
                return ((global::System.Drawing.Point)(this["Location_HIAnswerOption2"]));
            }
            set {
                this["Location_HIAnswerOption2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("उत्तर विकल्प 4")]
        public string HIAnswerOption4 {
            get {
                return ((string)(this["HIAnswerOption4"]));
            }
            set {
                this["HIAnswerOption4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8, 5")]
        public global::System.Drawing.Point Location_HIAnswerOption4 {
            get {
                return ((global::System.Drawing.Point)(this["Location_HIAnswerOption4"]));
            }
            set {
                this["Location_HIAnswerOption4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Copy Same>>")]
        public string Text_CopyAnswer {
            get {
                return ((string)(this["Text_CopyAnswer"]));
            }
            set {
                this["Text_CopyAnswer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("179, 0")]
        public global::System.Drawing.Point Location_CopyAnswer {
            get {
                return ((global::System.Drawing.Point)(this["Location_CopyAnswer"]));
            }
            set {
                this["Location_CopyAnswer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Save")]
        public string Text_SaveQuestion {
            get {
                return ((string)(this["Text_SaveQuestion"]));
            }
            set {
                this["Text_SaveQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("431, 10")]
        public global::System.Drawing.Point Location_SaveQuestion {
            get {
                return ((global::System.Drawing.Point)(this["Location_SaveQuestion"]));
            }
            set {
                this["Location_SaveQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cancel")]
        public string Text_CancelQuestion {
            get {
                return ((string)(this["Text_CancelQuestion"]));
            }
            set {
                this["Text_CancelQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6, 5")]
        public global::System.Drawing.Point Location_CancelQuestion {
            get {
                return ((global::System.Drawing.Point)(this["Location_CancelQuestion"]));
            }
            set {
                this["Location_CancelQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 24")]
        public global::System.Drawing.Point Location_panel_paragraphPopup {
            get {
                return ((global::System.Drawing.Point)(this["Location_panel_paragraphPopup"]));
            }
            set {
                this["Location_panel_paragraphPopup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("355, 146")]
        public global::System.Drawing.Size Size_panel_paragraphPopup {
            get {
                return ((global::System.Drawing.Size)(this["Size_panel_paragraphPopup"]));
            }
            set {
                this["Size_panel_paragraphPopup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Save and Next")]
        public string buttonSaveParagraphQuestionsAndNexe {
            get {
                return ((string)(this["buttonSaveParagraphQuestionsAndNexe"]));
            }
            set {
                this["buttonSaveParagraphQuestionsAndNexe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("431, 10")]
        public global::System.Drawing.Point Location_buttonSaveParagraphQuestionsAndNexe {
            get {
                return ((global::System.Drawing.Point)(this["Location_buttonSaveParagraphQuestionsAndNexe"]));
            }
            set {
                this["Location_buttonSaveParagraphQuestionsAndNexe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoLocationSave {
            get {
                return ((bool)(this["EnableAutoLocationSave"]));
            }
            set {
                this["EnableAutoLocationSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.8")]
        public string EmailHost {
            get {
                return ((string)(this["EmailHost"]));
            }
            set {
                this["EmailHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test@truworth.net")]
        public string EmailuserName {
            get {
                return ((string)(this["EmailuserName"]));
            }
            set {
                this["EmailuserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("soft20")]
        public string EmailPassword {
            get {
                return ((string)(this["EmailPassword"]));
            }
            set {
                this["EmailPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SecureConnection {
            get {
                return ((bool)(this["SecureConnection"]));
            }
            set {
                this["SecureConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Save and Next")]
        public string FinishParagraphQuestion {
            get {
                return ((string)(this["FinishParagraphQuestion"]));
            }
            set {
                this["FinishParagraphQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81, 12")]
        public global::System.Drawing.Point Location_FinishParagraph {
            get {
                return ((global::System.Drawing.Point)(this["Location_FinishParagraph"]));
            }
            set {
                this["Location_FinishParagraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Finish Paragraph Question")]
        public string Textbutton_closeParagraphQuestion {
            get {
                return ((string)(this["Textbutton_closeParagraphQuestion"]));
            }
            set {
                this["Textbutton_closeParagraphQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("261, 10")]
        public global::System.Drawing.Point Location_button_closeParagraphQuestion {
            get {
                return ((global::System.Drawing.Point)(this["Location_button_closeParagraphQuestion"]));
            }
            set {
                this["Location_button_closeParagraphQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210, 5")]
        public global::System.Drawing.Point AutoUpdateFormulaButton {
            get {
                return ((global::System.Drawing.Point)(this["AutoUpdateFormulaButton"]));
            }
            set {
                this["AutoUpdateFormulaButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto Update Formula")]
        public string TextAutoUpdateFormula {
            get {
                return ((string)(this["TextAutoUpdateFormula"]));
            }
            set {
                this["TextAutoUpdateFormula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Save Formula Image")]
        public string TextSaveFormulaImage {
            get {
                return ((string)(this["TextSaveFormulaImage"]));
            }
            set {
                this["TextSaveFormulaImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("463, 2")]
        public global::System.Drawing.Point Location_SaveFormulaImage {
            get {
                return ((global::System.Drawing.Point)(this["Location_SaveFormulaImage"]));
            }
            set {
                this["Location_SaveFormulaImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6, 231")]
        public global::System.Drawing.Point Calc_Devide {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Devide"]));
            }
            set {
                this["Calc_Devide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 232")]
        public global::System.Drawing.Point Calc_Multiply {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Multiply"]));
            }
            set {
                this["Calc_Multiply"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("74, 232")]
        public global::System.Drawing.Point Calc_PM {
            get {
                return ((global::System.Drawing.Point)(this["Calc_PM"]));
            }
            set {
                this["Calc_PM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("108, 232")]
        public global::System.Drawing.Point Calc_root {
            get {
                return ((global::System.Drawing.Point)(this["Calc_root"]));
            }
            set {
                this["Calc_root"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("142, 232")]
        public global::System.Drawing.Point Calc_Integration {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Integration"]));
            }
            set {
                this["Calc_Integration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("176, 232")]
        public global::System.Drawing.Point Calc_fi {
            get {
                return ((global::System.Drawing.Point)(this["Calc_fi"]));
            }
            set {
                this["Calc_fi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210, 232")]
        public global::System.Drawing.Point Calc_NotEQ {
            get {
                return ((global::System.Drawing.Point)(this["Calc_NotEQ"]));
            }
            set {
                this["Calc_NotEQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("244, 232")]
        public global::System.Drawing.Point Calc_PI {
            get {
                return ((global::System.Drawing.Point)(this["Calc_PI"]));
            }
            set {
                this["Calc_PI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("278, 231")]
        public global::System.Drawing.Point Calc_Summession {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Summession"]));
            }
            set {
                this["Calc_Summession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("312, 231")]
        public global::System.Drawing.Point Calc_Omega {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Omega"]));
            }
            set {
                this["Calc_Omega"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("346, 229")]
        public global::System.Drawing.Point Calc_Vector {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Vector"]));
            }
            set {
                this["Calc_Vector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("390, 230")]
        public global::System.Drawing.Point Calc_Cdot {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Cdot"]));
            }
            set {
                this["Calc_Cdot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6, 273")]
        public global::System.Drawing.Point Calc_LeftCurly {
            get {
                return ((global::System.Drawing.Point)(this["Calc_LeftCurly"]));
            }
            set {
                this["Calc_LeftCurly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 273")]
        public global::System.Drawing.Point Calc_RightCurly {
            get {
                return ((global::System.Drawing.Point)(this["Calc_RightCurly"]));
            }
            set {
                this["Calc_RightCurly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("74, 273")]
        public global::System.Drawing.Point Calc_leftMetrix {
            get {
                return ((global::System.Drawing.Point)(this["Calc_leftMetrix"]));
            }
            set {
                this["Calc_leftMetrix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("108, 273")]
        public global::System.Drawing.Point Calc_RightMatrix {
            get {
                return ((global::System.Drawing.Point)(this["Calc_RightMatrix"]));
            }
            set {
                this["Calc_RightMatrix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("142, 273")]
        public global::System.Drawing.Point Calc_LeftBracket {
            get {
                return ((global::System.Drawing.Point)(this["Calc_LeftBracket"]));
            }
            set {
                this["Calc_LeftBracket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("176, 273")]
        public global::System.Drawing.Point Calc_RightBracket {
            get {
                return ((global::System.Drawing.Point)(this["Calc_RightBracket"]));
            }
            set {
                this["Calc_RightBracket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210, 271")]
        public global::System.Drawing.Point Calc_Delta {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Delta"]));
            }
            set {
                this["Calc_Delta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("244, 271")]
        public global::System.Drawing.Point Calc_Alpha {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Alpha"]));
            }
            set {
                this["Calc_Alpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("278, 273")]
        public global::System.Drawing.Point Calc_Beta {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Beta"]));
            }
            set {
                this["Calc_Beta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("312, 273")]
        public global::System.Drawing.Point Calc_Gamma {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Gamma"]));
            }
            set {
                this["Calc_Gamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("346, 273")]
        public global::System.Drawing.Point Calc_Delta1 {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Delta1"]));
            }
            set {
                this["Calc_Delta1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("380, 273")]
        public global::System.Drawing.Point Calc_Epsilon {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Epsilon"]));
            }
            set {
                this["Calc_Epsilon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("414, 271")]
        public global::System.Drawing.Point Calc_Mu {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Mu"]));
            }
            set {
                this["Calc_Mu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("482, 273")]
        public global::System.Drawing.Point Calc_psi {
            get {
                return ((global::System.Drawing.Point)(this["Calc_psi"]));
            }
            set {
                this["Calc_psi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("516, 273")]
        public global::System.Drawing.Point Calc_Theta {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Theta"]));
            }
            set {
                this["Calc_Theta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("550, 271")]
        public global::System.Drawing.Point Calc_RationalR {
            get {
                return ((global::System.Drawing.Point)(this["Calc_RationalR"]));
            }
            set {
                this["Calc_RationalR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6, 313")]
        public global::System.Drawing.Point Calc_Pow {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Pow"]));
            }
            set {
                this["Calc_Pow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("73, 313")]
        public global::System.Drawing.Point Calc_a_div_b {
            get {
                return ((global::System.Drawing.Point)(this["Calc_a_div_b"]));
            }
            set {
                this["Calc_a_div_b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140, 313")]
        public global::System.Drawing.Point Calc_LeftEq {
            get {
                return ((global::System.Drawing.Point)(this["Calc_LeftEq"]));
            }
            set {
                this["Calc_LeftEq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("201, 313")]
        public global::System.Drawing.Point Calc_RightEQ {
            get {
                return ((global::System.Drawing.Point)(this["Calc_RightEQ"]));
            }
            set {
                this["Calc_RightEQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 342")]
        public global::System.Drawing.Point Calc_SIN {
            get {
                return ((global::System.Drawing.Point)(this["Calc_SIN"]));
            }
            set {
                this["Calc_SIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 342")]
        public global::System.Drawing.Point Calc_SINH {
            get {
                return ((global::System.Drawing.Point)(this["Calc_SINH"]));
            }
            set {
                this["Calc_SINH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("153, 342")]
        public global::System.Drawing.Point Calc_COS {
            get {
                return ((global::System.Drawing.Point)(this["Calc_COS"]));
            }
            set {
                this["Calc_COS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 342")]
        public global::System.Drawing.Point Calc_COSH {
            get {
                return ((global::System.Drawing.Point)(this["Calc_COSH"]));
            }
            set {
                this["Calc_COSH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("301, 342")]
        public global::System.Drawing.Point Calc_Tan {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Tan"]));
            }
            set {
                this["Calc_Tan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("380, 342")]
        public global::System.Drawing.Point Calc_TanH {
            get {
                return ((global::System.Drawing.Point)(this["Calc_TanH"]));
            }
            set {
                this["Calc_TanH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("449, 342")]
        public global::System.Drawing.Point Calc_Infite {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Infite"]));
            }
            set {
                this["Calc_Infite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 371")]
        public global::System.Drawing.Point Calc_Limit {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Limit"]));
            }
            set {
                this["Calc_Limit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("74, 371")]
        public global::System.Drawing.Point Calc_Expo {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Expo"]));
            }
            set {
                this["Calc_Expo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("143, 371")]
        public global::System.Drawing.Point Calc_Matrix {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Matrix"]));
            }
            set {
                this["Calc_Matrix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6, 398")]
        public global::System.Drawing.Point Calc_Overline {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Overline"]));
            }
            set {
                this["Calc_Overline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 398")]
        public global::System.Drawing.Point Calc_Underline {
            get {
                return ((global::System.Drawing.Point)(this["Calc_Underline"]));
            }
            set {
                this["Calc_Underline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("626, 172")]
        public global::System.Drawing.Point Calc_ShowFormula {
            get {
                return ((global::System.Drawing.Point)(this["Calc_ShowFormula"]));
            }
            set {
                this["Calc_ShowFormula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23, 19")]
        public global::System.Drawing.Point Calc_PicZoom {
            get {
                return ((global::System.Drawing.Point)(this["Calc_PicZoom"]));
            }
            set {
                this["Calc_PicZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Atou positioning")]
        public string TabMenu4 {
            get {
                return ((string)(this["TabMenu4"]));
            }
            set {
                this["TabMenu4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EditorFonts")]
        public string TabMenu3 {
            get {
                return ((string)(this["TabMenu3"]));
            }
            set {
                this["TabMenu3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sort Keys")]
        public string TabMenu2 {
            get {
                return ((string)(this["TabMenu2"]));
            }
            set {
                this["TabMenu2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application General")]
        public string TabMenu1 {
            get {
                return ((string)(this["TabMenu1"]));
            }
            set {
                this["TabMenu1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9, 18")]
        public global::System.Drawing.Point Location_Setting_G5 {
            get {
                return ((global::System.Drawing.Point)(this["Location_Setting_G5"]));
            }
            set {
                this["Location_Setting_G5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("269, 18")]
        public global::System.Drawing.Point Location_Setting_G6 {
            get {
                return ((global::System.Drawing.Point)(this["Location_Setting_G6"]));
            }
            set {
                this["Location_Setting_G6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("529, 18")]
        public global::System.Drawing.Point Location_Setting_G7 {
            get {
                return ((global::System.Drawing.Point)(this["Location_Setting_G7"]));
            }
            set {
                this["Location_Setting_G7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18, 25")]
        public global::System.Drawing.Point Location_Setting_G4 {
            get {
                return ((global::System.Drawing.Point)(this["Location_Setting_G4"]));
            }
            set {
                this["Location_Setting_G4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 14")]
        public global::System.Drawing.Point Location_Setting_G2 {
            get {
                return ((global::System.Drawing.Point)(this["Location_Setting_G2"]));
            }
            set {
                this["Location_Setting_G2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350, 14")]
        public global::System.Drawing.Point Location_Setting_G3 {
            get {
                return ((global::System.Drawing.Point)(this["Location_Setting_G3"]));
            }
            set {
                this["Location_Setting_G3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9, 14")]
        public global::System.Drawing.Point Location_Setting_G1 {
            get {
                return ((global::System.Drawing.Point)(this["Location_Setting_G1"]));
            }
            set {
                this["Location_Setting_G1"] = value;
            }
        }
    }
}
