//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astrila.Eq2ImgWinForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LinkDialogURLs {
            get {
                return ((string)(this["LinkDialogURLs"]));
            }
            set {
                this["LinkDialogURLs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoUpdateFormula {
            get {
                return ((bool)(this["AutoUpdateFormula"]));
            }
            set {
                this["AutoUpdateFormula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormulaImages")]
        public string FormulaImages {
            get {
                return ((string)(this["FormulaImages"]));
            }
            set {
                this["FormulaImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color BackGroundColor {
            get {
                return ((global::System.Drawing.Color)(this["BackGroundColor"]));
            }
            set {
                this["BackGroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color FontColor {
            get {
                return ((global::System.Drawing.Color)(this["FontColor"]));
            }
            set {
                this["FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font ApplicationFont {
            get {
                return ((global::System.Drawing.Font)(this["ApplicationFont"]));
            }
            set {
                this["ApplicationFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("184")]
        public int SplitContainer9Height {
            get {
                return ((int)(this["SplitContainer9Height"]));
            }
            set {
                this["SplitContainer9Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("186")]
        public int SplitContainer8Height {
            get {
                return ((int)(this["SplitContainer8Height"]));
            }
            set {
                this["SplitContainer8Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("327")]
        public int SplitContainer2Height {
            get {
                return ((int)(this["SplitContainer2Height"]));
            }
            set {
                this["SplitContainer2Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("315")]
        public int SplitContainer5Height {
            get {
                return ((int)(this["SplitContainer5Height"]));
            }
            set {
                this["SplitContainer5Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("88")]
        public int SplitContainer7Height {
            get {
                return ((int)(this["SplitContainer7Height"]));
            }
            set {
                this["SplitContainer7Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("88")]
        public int SplitContainer6Height {
            get {
                return ((int)(this["SplitContainer6Height"]));
            }
            set {
                this["SplitContainer6Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int SplitContainer4Height {
            get {
                return ((int)(this["SplitContainer4Height"]));
            }
            set {
                this["SplitContainer4Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87")]
        public int SplitContainer3Height {
            get {
                return ((int)(this["SplitContainer3Height"]));
            }
            set {
                this["SplitContainer3Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("623")]
        public int SplitContainer1Height {
            get {
                return ((int)(this["SplitContainer1Height"]));
            }
            set {
                this["SplitContainer1Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveAllSplitEnabled {
            get {
                return ((bool)(this["SaveAllSplitEnabled"]));
            }
            set {
                this["SaveAllSplitEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoSizePanels {
            get {
                return ((bool)(this["EnableAutoSizePanels"]));
            }
            set {
                this["EnableAutoSizePanels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Alt+F")]
        public global::System.Windows.Forms.Keys OpenFormulaPanel {
            get {
                return ((global::System.Windows.Forms.Keys)(this["OpenFormulaPanel"]));
            }
            set {
                this["OpenFormulaPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Alt+V")]
        public global::System.Windows.Forms.Keys CustomPaste {
            get {
                return ((global::System.Windows.Forms.Keys)(this["CustomPaste"]));
            }
            set {
                this["CustomPaste"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Alt+V")]
        public string CustomPasteKeysDisplay {
            get {
                return ((string)(this["CustomPasteKeysDisplay"]));
            }
            set {
                this["CustomPasteKeysDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DefultFontSize {
            get {
                return ((int)(this["DefultFontSize"]));
            }
            set {
                this["DefultFontSize"] = value;
            }
        }
    }
}
