//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Log
    {
        public int Error_ID { get; set; }
        public Nullable<System.DateTime> Error_Date { get; set; }
        public string Error_Msg { get; set; }
        public string Error_Number { get; set; }
        public string Error_Source { get; set; }
    }
}
