//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionDetail
    {
        public int QueOptionID { get; set; }
        public int QueOption_QuestionID { get; set; }
        public string QueOption_Eng { get; set; }
        public string QueOption_Hindi { get; set; }
        public string QueOption_Other { get; set; }
        public int QueOption_Sqn { get; set; }
    
        public virtual QuestionMaster QuestionMaster { get; set; }
    }
}
