//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionMaster
    {
        public QuestionMaster()
        {
            this.QuestionDetails = new HashSet<QuestionDetail>();
        }
    
        public int QuestionID { get; set; }
        public int QueSubjectID { get; set; }
        public int QueSubSubjectID { get; set; }
        public string QueTitleEng { get; set; }
        public string QueTitleHindi { get; set; }
        public string QueTitleOther { get; set; }
        public bool QueIsActive { get; set; }
        public int QueCreateBy { get; set; }
        public System.DateTime QueCreateOn { get; set; }
        public bool QueIsApproved { get; set; }
        public Nullable<System.DateTime> QueModifyOn { get; set; }
        public Nullable<int> QueModifyBy { get; set; }
    
        public virtual ICollection<QuestionDetail> QuestionDetails { get; set; }
    }
}
