//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSubjectMaster
    {
        public int SubSubjectID { get; set; }
        public int SubSubjectMasterID { get; set; }
        public string SubSubjectName { get; set; }
        public bool SubSubjectIsActive { get; set; }
        public System.DateTime SubSubjectCreateOn { get; set; }
    
        public virtual SubjectMaster SubjectMaster { get; set; }
    }
}
