//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserLoginID { get; set; }
        public byte[] UserPassword { get; set; }
        public int UserRoleID { get; set; }
        public string UserEmailID { get; set; }
        public string UserContactNo { get; set; }
        public bool UserIsActive { get; set; }
        public System.DateTime UserCreateOn { get; set; }
    
        public virtual RoleMaster RoleMaster { get; set; }
    }
}
